# env and task
env:
  name: MiniGrid-Empty-5x5-v0 # MiniGrid environment for discrete action space
  task: ""
  library: minari
  n_samples_stats: 1000
  seed: 0
  backend: gymnasium  
  
# logger
logger:
  backend: wandb
  project_name: torchrl_example_cql
  group_name: null
  exp_name: cql_${replay_buffer.dataset}
  eval_iter: 5000         # eval interval in gradient steps
  eval_steps: 1000        # evaluation steps per eval
  mode: online
  eval_envs: 5
  video: True

# replay buffer
replay_buffer:
  env: CartPole-v1
  dataset: CartPole-v1-random-v0
  batch_size: 128
  episodes: 1000

# optimization
optim:
  device: null
  lr: 3e-4               # learning rate
  weight_decay: 0.0
  gradient_steps: 100_000
  policy_eval_start: 40_000

# model
model:
  hidden_sizes: [256, 256]
  activation: relu

# loss
loss: 
  loss_function: l2
  gamma: 0.99
  tau: 0.005
  # CQL specific hyperparameters
  temperature: 1.0
  min_q_weight: 1.0
  max_q_backup: False
  deterministic_backup: False
  num_random: 10
  with_lagrange: True
  lagrange_thresh: 5.0

compile:
  compile: False
  compile_mode:
  cudagraphs: False